DELETE http://localhost:3001/api/blogs/66bf042bc5d8fb15d9a9be6f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpaWFub21hIiwiaWQiOiI2NmJmMmY0NDkyOWRmODk1ZDZjY2NhZDgiLCJpYXQiOjE3MjQwNjM4NjEsImV4cCI6MTcyNDA2NzQ2MX0.onI5DHR9BcJ0iCMiHMP2alatlh39nqxAT4hP6vtgQik
