POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpaWFub21hIiwiaWQiOiI2NmJmMmY0NDkyOWRmODk1ZDZjY2NhZDgiLCJpYXQiOjE3MjQwNjM4NjEsImV4cCI6MTcyNDA2NzQ2MX0.onI5DHR9BcJ0iCMiHMP2alatlh39nqxAT4hP6vtgQik

{
    "title": "Testi32",
    "author": "tiia",
    "url": "http://www.tiablogi.com",
    "likes": 600
}