POST http://localhost:3001/api/patients
Content-type: application/json; charset=utf-8

{
        "name": "Testi testinen",
        "dateOfBirth": "1996-10-09",
        "ssn": "090796-123C",
        "gender": "le",
        "occupation": "Ilmajoki"
}