POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpdWh0aSIsImlkIjoiNjZiZTM5ZTQxNjk3Mzk0MmE1MDEzNzE5IiwiaWF0IjoxNzIzNzQ0NDcwfQ.ZMxMSUSH5nTipQhdkoSmHV4rWCHgp-E9BVDZvxMOuwY

{
    "content" : "User-testi 2",
    "important" : true
}